version: '3.8'

services:
  bot:
    build: .
    volumes:
      - .:/app
      - ./data:/app/data
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - TELEGRAM_API_ID=${TELEGRAM_API_ID}
      - TELEGRAM_API_HASH=${TELEGRAM_API_HASH}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TARGET_CHANNELS=${TARGET_CHANNELS}
      - DATABASE_URL=sqlite+aiosqlite:///data/qa_bot.db
      - VECTOR_STORE_PATH=/app/data/vector_store
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import sqlite3; sqlite3.connect('/app/data/qa_bot.db')"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Optional service for running migrations separately (useful in CI/CD)
  migrations:
    build: .
    volumes:
      - .:/app
      - ./data:/app/data
    environment:
      - DATABASE_URL=sqlite+aiosqlite:///data/qa_bot.db
    command: python -m alembic upgrade head
    profiles:
      - migrations